import { extendTheme } from "@chakra-ui/react";

const theme = extendTheme({
    styles:{
        global:{
            html:{
                fontSize:"17px"
            },
            body:{
                bg:'brand.whiteColor'
            },
            m:'0'
        },
    },
    fonts:{
        heading: `Urbanist,'Segoe UI', Tahoma, Geneva, Verdana, sans-serif`,
        body: `Urbanist,'Segoe UI', Tahoma, Geneva, Verdana, sans-serif`,
    },
    
    colors:{
        brand:{
            whiteColor:'#f5f5f5',
            blackColor:'#454545',
            primaryColor:'#ba94d1',
            accentColor:'#7f669d'
        }
    },
    components:{
        Stack:{
            baseStyle:{
                bg:'#ffffff'
            }
        },
        VStack:{
            baseStyle:{
                bg:'#ffffff'
            }
        },

        Text:{
            baseStyle:{
                fontSize:'1rem',
                fontWeight:'normal',
                letterSpacing:'0.029',
            },
            variants:{
                'body2':{
                    fontSize:'0.882rem',
                    letterSpacing:'0.015rem'
                },
                'sub2':{
                    fontWeight:'500',
                    fontSize:'0.824rem',
                    letterSpacing:'0.006rem',
                    color:'brand.primaryColor'
                },
                'cap':{
                    fontSize:'0.725rem',
                    letterSpacing:'0.024rem'
                },
                'sub1':{
                    fontWeight:'normal',
                    fontSize:'1rem',
                    letterSpacing:'0.009rem'
                }
            },
        },
        Heading:{
            baseStyle:{
                color:'brand.blackColor'
            },
            variants:{
                'headline1':{
                    fontWeight:'normal',
                    fontSize:'2rem',
                    letterSpacing:'0.015rem',
                    color:'brand.accentColor'
                },
                'headline2':{
                    fontWeight:'normal',
                    fontSize:'1.471rem',
                    letterSpacing:'0',
                    color:'brand.accentColor'
                },
                'headline3':{
                    fontWeight:'500',
                    fontSize:'1.176rem',
                    letterSpacing:'0.009rem'
                },
                'subtitle1':{
                    fontWeight:'normal',
                    fontSize:'1rem',
                    letterSpacing:'0.009rem'
                }
            }
        },
        CloseButton:{
            variants:{
                'drawerBtn':{
                    color:'brand.accentColor',
                    fontSize:'md',
                    mt:'3',
                    _hover:{
                        bg: 'transparent'
                    },
                    _active:{
                        color:'brand.primaryColor'
                    }
                }
            }
        },
        Drawer:{
            baseStyle:{
                dialog:{
                    bg:'brand.whiteColor'
                }
            }
        },
        Button:{
            variants:{
                'drawerBtn':{
                    color:'brand.accentColor',
                    _active:{
                        color:'brand.primaryColor',
                    }
                },
                'navItem':{
                    color:'brand.blackColor',
                    letterSpacing:'0.029rem',
                    fontWeight:'normal',
                    fontSize:'1rem',
                    paddingLeft:'0',
                    position: 'relative',
                    zIndex:'1',
                    _hover:{
                        _before:{
                            content:'""',
                            display:'block',
                            position:'absolute',
                            width:'80%',
                            height:'0.8rem',
                            top: '1.3rem',
                            left:'0',
                            zIndex:'-1',
                            backgroundColor:'brand.primaryColor',
                        }
                    }
                },
                outline:{
                    color:'brand.blackColor',
                    letterSpacing:'0.074rem',
                    fontWeight:'500',
                    borderColor:'brand.blackColor',
                    borderRadius:'0.235rem',
                    backgroundColor:'brand.whiteColor',
                    fontSize:'0.882rem',
                    _after:{
                        content:'""',
                        display:'block',
                        position:'absolute',
                        zIndex:'-1',
                        width:'96%',
                        height:'100%',
                        bottom:'-4px',
                        left:'calc(50% - 48%)',
                        borderRadius:'0.235rem',
                        border:'1px solid',
                        borderColor:'brand.blackColor',
                        backgroundColor:'brand.whiteColor',
                    },
                    _hover:{
                        backgroundColor:'brand.primaryColor',
                        _after:{
                            backgroundColor:'brand.accentColor'
                        }
                    },
                    _active:{
                        backgroundColor:'brand.accentColor',
                        _after:{
                            backgroundColor:'brand.primaryColor'
                        }
                    }
                }
            }
        }
    }
});

export default theme;